function Import-PreferencePolicySetting {
    <#
    .SYNOPSIS
        Applies Group Policy Preference rows from the CSV/Excel schema to a GPO.
    .DESCRIPTION
        Routes each row to the appropriate import mechanism:
          - 'Windows Registry' category rows: written via Set-GPPrefRegistryValue
          - All other Preference categories: XML is generated by ConvertTo-GPPreferenceXml
            and written to SYSVOL (or a local staging directory) via Update-GPOVersion.

        Rows for the same Category + Scope are batched so that a single XML file is
        written per preference type per GPO, rather than one file per row.
    .PARAMETER Rows
        One or more PSCustomObjects with the standard 12-column GPO setting schema.
        All rows must belong to the same GPO.
    .PARAMETER GPOName
        Target GPO display name. If provided, overrides the GPOName in the rows.
    .PARAMETER GPOGuid
        Target GPO GUID (required for SYSVOL write path).
    .PARAMETER Domain
        DNS domain of the GPO.
    .PARAMETER LocalFallbackPath
        Staging directory used by Update-GPOVersion when not running as Domain Admin.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [PSCustomObject[]]$Rows,

        [Parameter()]
        [string]$GPOName,

        [Parameter(Mandatory)]
        [string]$GPOGuid,

        [Parameter(Mandatory)]
        [string]$Domain,

        [Parameter()]
        [string]$LocalFallbackPath = (Get-Location).Path
    )

    begin {
        Get-CallerPreference -Cmdlet $PSCmdlet -SessionState $ExecutionContext.SessionState
    }

    process {
        $targetGPO = if ($PSBoundParameters.ContainsKey('GPOName') -and $GPOName) { $GPOName } else { $Rows[0].GPOName }

        # Separate Windows Registry rows (handled by Set-GPPrefRegistryValue) from XML-based rows
        $registryRows = $Rows | Where-Object { $_.Category -eq 'Windows Registry' }
        $xmlRows      = $Rows | Where-Object { $_.Category -ne 'Windows Registry' }

        # ---- Windows Registry preference rows ----
        foreach ($row in $registryRows) {
            $typeKey = $row.ValueType.ToUpper().Trim()
            if (-not $script:RegistryTypeMap.ContainsKey($typeKey)) {
                Write-Warning "Import-PreferencePolicySetting: unknown ValueType '$($row.ValueType)' for '$($row.SettingName)'; defaulting to REG_SZ."
                $typeKey = 'REG_SZ'
            }
            $valueKind = $script:RegistryTypeMap[$typeKey]

            $typedValue = switch ($typeKey) {
                'REG_DWORD'    { [int32]$row.Value }
                'REG_QWORD'    { [int64]$row.Value }
                'REG_MULTI_SZ' { [string[]]($row.Value -split '\|') }
                default        { [string]$row.Value }
            }

            Write-Verbose "Import-PreferencePolicySetting: Registry pref $($row.Scope)\$($row.RegistryKey)\$($row.RegistryValueName)"

            $splat = @{
                Name        = $targetGPO
                Domain      = $Domain
                Key         = $row.RegistryKey
                ValueName   = $row.RegistryValueName
                Type        = $valueKind
                Value       = $typedValue
                Action      = 'Update'
                ErrorAction = 'Stop'
            }
            if ($row.Scope -eq 'User') {
                Set-GPPrefRegistryValue @splat -Context User
            } else {
                Set-GPPrefRegistryValue @splat -Context Computer
            }
        }

        # ---- XML-based preference rows ----
        # Group by Scope + Category so we write one XML file per combination
        $xmlGroups = $xmlRows | Group-Object -Property { "$($_.Scope)|$($_.Category)" }

        foreach ($group in $xmlGroups) {
            $parts    = $group.Name -split '\|', 2
            $rowScope = $parts[0]
            $rowCat   = $parts[1]

            if (-not $script:PreferenceSYSVOLMap.ContainsKey($rowCat)) {
                Write-Warning "Import-PreferencePolicySetting: category '$rowCat' has no SYSVOL mapping; skipping."
                continue
            }

            Write-Verbose "Import-PreferencePolicySetting: generating XML for '$rowCat' ($rowScope) — $($group.Group.Count) row(s)."

            $xmlContent = ConvertTo-GPPreferenceXml -Rows $group.Group -Category $rowCat -Scope $rowScope

            $updateResult = Update-GPOVersion `
                -GPOGuid          $GPOGuid `
                -Domain           $Domain `
                -Scope            $rowScope `
                -Category         $rowCat `
                -XmlContent       $xmlContent `
                -LocalFallbackPath $LocalFallbackPath

            if (-not $updateResult.Success) {
                Write-Warning "Import-PreferencePolicySetting: Update-GPOVersion failed for '$rowCat' ($rowScope)."
            }
        }
    }
}
